# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip_online.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(210, 120, 281, 32))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lIpStart = QtWidgets.QLineEdit(Form)
        self.lIpStart.setGeometry(QtCore.QRect(34, 45, 269, 46))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.lIpStart.setFont(font)
        self.lIpStart.setObjectName("lIpStart")
        self.label_zhi = QtWidgets.QLabel(Form)
        self.label_zhi.setGeometry(QtCore.QRect(313, 44, 29, 35))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.label_zhi.setFont(font)
        self.label_zhi.setObjectName("label_zhi")
        self.pushCheckOneLine = QtWidgets.QPushButton(Form)
        self.pushCheckOneLine.setGeometry(QtCore.QRect(40, 120, 150, 46))
        self.pushCheckOneLine.setObjectName("pushCheckOneLine")
        self.lIpEnd = QtWidgets.QLineEdit(Form)
        self.lIpEnd.setEnabled(True)
        self.lIpEnd.setGeometry(QtCore.QRect(352, 45, 269, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lIpEnd.sizePolicy().hasHeightForWidth())
        self.lIpEnd.setSizePolicy(sizePolicy)
        self.lIpEnd.setMinimumSize(QtCore.QSize(0, 0))
        self.lIpEnd.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.lIpEnd.setFont(font)
        self.lIpEnd.setObjectName("lIpEnd")
        self.pushConfigIp = QtWidgets.QPushButton(Form)
        self.pushConfigIp.setGeometry(QtCore.QRect(631, 44, 150, 49))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.pushConfigIp.setFont(font)
        self.pushConfigIp.setObjectName("pushConfigIp")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 200, 731, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_zhi.setText(_translate("Form", "至"))
        self.pushCheckOneLine.setText(_translate("Form", "检查"))
        self.pushConfigIp.setText(_translate("Form", "保存"))
