# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_changeip.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(847, 770)
        self.line_currip = QtWidgets.QLineEdit(Form)
        self.line_currip.setGeometry(QtCore.QRect(240, 90, 431, 28))
        self.line_currip.setObjectName("line_currip")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 90, 191, 21))
        self.label.setObjectName("label")
        self.btn_last = QtWidgets.QPushButton(Form)
        self.btn_last.setGeometry(QtCore.QRect(240, 140, 101, 40))
        self.btn_last.setObjectName("btn_last")
        self.btn_next = QtWidgets.QPushButton(Form)
        self.btn_next.setGeometry(QtCore.QRect(370, 140, 101, 40))
        self.btn_next.setObjectName("btn_next")
        self.btn_save_config = QtWidgets.QPushButton(Form)
        self.btn_save_config.setGeometry(QtCore.QRect(490, 140, 191, 40))
        self.btn_save_config.setObjectName("btn_save_config")
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setGeometry(QtCore.QRect(690, 90, 191, 21))
        self.label_info.setObjectName("label_info")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "当前配置文件IP为"))
        self.btn_last.setText(_translate("Form", "上一个"))
        self.btn_next.setText(_translate("Form", "下一个"))
        self.btn_save_config.setText(_translate("Form", "保存到配置文件"))
        self.label_info.setText(_translate("Form", "--"))
