# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(810, 319)
        self.lab1 = QtWidgets.QLabel(Form)
        self.lab1.setGeometry(QtCore.QRect(10, 40, 171, 24))
        self.lab1.setObjectName("lab1")
        self.line_sip_ip = QtWidgets.QLineEdit(Form)
        self.line_sip_ip.setGeometry(QtCore.QRect(200, 40, 291, 31))
        self.line_sip_ip.setObjectName("line_sip_ip")
        self.btn_open = QtWidgets.QPushButton(Form)
        self.btn_open.setGeometry(QtCore.QRect(510, 90, 132, 40))
        self.btn_open.setObjectName("btn_open")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 171, 24))
        self.label_2.setObjectName("label_2")
        self.line_cfg_path = QtWidgets.QLineEdit(Form)
        self.line_cfg_path.setGeometry(QtCore.QRect(200, 100, 291, 31))
        self.line_cfg_path.setObjectName("line_cfg_path")
        self.line_ip_section = QtWidgets.QLineEdit(Form)
        self.line_ip_section.setGeometry(QtCore.QRect(200, 160, 51, 31))
        self.line_ip_section.setObjectName("line_ip_section")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 171, 24))
        self.label_3.setObjectName("label_3")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(290, 160, 121, 24))
        self.label_31.setObjectName("label_31")
        self.line_ip_start = QtWidgets.QLineEdit(Form)
        self.line_ip_start.setGeometry(QtCore.QRect(400, 160, 61, 31))
        self.line_ip_start.setObjectName("line_ip_start")
        self.line_ip_step = QtWidgets.QLineEdit(Form)
        self.line_ip_step.setGeometry(QtCore.QRect(580, 160, 61, 31))
        self.line_ip_step.setObjectName("line_ip_step")
        self.lab_32 = QtWidgets.QLabel(Form)
        self.lab_32.setGeometry(QtCore.QRect(500, 160, 121, 24))
        self.lab_32.setObjectName("lab_32")
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setGeometry(QtCore.QRect(530, 250, 132, 40))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lab1.setText(_translate("Form", "SIP服务器地址"))
        self.btn_open.setText(_translate("Form", "打开"))
        self.label_2.setText(_translate("Form", "配置文件地址"))
        self.label_3.setText(_translate("Form", "配置IP网段"))
        self.label_31.setText(_translate("Form", "起始IP值"))
        self.lab_32.setText(_translate("Form", "步进"))
        self.btn_ok.setText(_translate("Form", "OK"))
